### ISSUE TITLE
Allow use of free API 

### ISSUE THREAD

**Issue by ToferC** [mgruner/deepl-api-rs#1]
First - thanks so much for putting this together. I'd like to test it out, but I have the free tier of the DeepL api. Would it be possible to add an option for using free tier vs paid? (I think this just needs a different url for the request).

If not, I'll fork and uodate, but I think making it easier for people to set up their apps and test makes sense for the main repo. Thanks.

**Comment by mgruner** [comment]
Hi @ToferC. Thanks a lot for the pointer - when I created this, there was no free tier. I will check and fix this.
Looking at [their documentation](https://www.deepl.com/docs-api/accessing-the-api/general-information/) it seems that the URL does not need to be configurable as it can be inferred from the API key.

**Comment by ToferC** [comment]
I forked and set up a light integration that takes another .env variable to update the query URL. I tried with just the free API Key, but it didn't work. Unfortunately, I'm now having an issue calling the API from an actix-web runtime because of the blocking request. I may see if I can rebuild for use with the framework, but I'm not great at async work, so we'll see.

Link to the fork here: https://github.com/ToferC/deepl-api-rs

Happy to submit a pull request (I'd just want to update the docs a bit).

**Comment by mgruner** [comment]
Hi @ToferC, could you please check if 64e382e2ef4af4742e8bbf188146c35ea4f3b6e8 fixes the issue with the free tier API endpoint? It works for me, and requires no interface changes. I would then proceed to build a new version.

**Comment by ToferC** [comment]
Confirmed that this works with the free endpoint. Thanks for the update!

In case you might be interested, I continued to tweak your crate to get it working with the async actix_web framework (which still requires tokio=0.2). I've got it working in test and will be pushing to production today. The only bit I'd need to go back and re-add is async tests.

Great work and take care!

**Comment by mgruner** [comment]
@ToferC thanks for the update. I'm open for adding async capabilities to the API in case you want to contribute. I have no experience with async in Rust just yet, though.
